import React, {Component} from 'react';
import Card from './styles/Card';
import GridItem from './styles/GridItem';

export default class GridContainer extends Component {
  state = {
    boxes: [
      {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }, {
        initials: ''
      }
    ]
  }
  render() {
    const {boxes} = this.state;
    return (
      <Card>
        {boxes.map((box, index) => (
          <GridItem key={index}>
            {index + 1}
          </GridItem>
        ))}
      </Card>
    )
  }
}
